backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "responsive-web-design" 
    label: "Course - Responsive Web Design"
    folder: "src/pages/course/responsive-web-design"
    create: true
    slug: "{{slug}}"
    identifier_field: title
    fields: 
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "course-page"}
      - {label: Title, name: title, widget: string}
      - {label: Order, name: order, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}
